require_relative "calc/version"
require_relative "calc/errors"
require_relative "calc/parser"
require_relative "calc/builtins"
require_relative "calc/functions"
require_relative "calc/namespace_registry"
require_relative "calc/executer"
require_relative "calc/environment"
